package calculadora;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;

/**
 *
 * @author Prof. Moisés Henrique Ramos Pereira
 */
public class TelinhaCalculadora extends javax.swing.JFrame {

    static int p = 0;
    String textoCalculo;
    Double resultado;

    /**
     * Creates new form TelinhaCalculadora
     */
    public TelinhaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextArea_Historico = new javax.swing.JTextArea();
        Calculo = new javax.swing.JTextField();
        jTextField_a = new javax.swing.JTextField();
        jTextField_b = new javax.swing.JTextField();
        jTextField_c = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora do Poder");
        setResizable(false);

        jTextArea_Historico.setEditable(false);
        jTextArea_Historico.setColumns(20);
        jTextArea_Historico.setForeground(new java.awt.Color(39, 36, 36));
        jTextArea_Historico.setRows(5);
        jTextArea_Historico.setAutoscrolls(false);
        jTextArea_Historico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea_Historico.setDisabledTextColor(new java.awt.Color(44, 41, 38));
        jTextArea_Historico.setEnabled(false);

        Calculo.setAutoscrolls(false);

        jTextField_a.setAutoscrolls(false);
        jTextField_a.setDisabledTextColor(new java.awt.Color(44, 41, 38));

        jTextField_b.setAutoscrolls(false);
        jTextField_b.setDisabledTextColor(new java.awt.Color(44, 41, 38));

        jTextField_c.setAutoscrolls(false);
        jTextField_c.setDisabledTextColor(new java.awt.Color(44, 41, 38));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel1.setText("  x²  +");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel2.setText("  =    0");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel3.setText("  x  + ");

        jButton15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton15.setText("×");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton16.setText("÷");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton17.setText("=");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton10.setText("0");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton11.setText("%");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton12.setText(".");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton13.setText("+");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton14.setText("-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton18.setText("<-");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton19.setText("C");
        jButton19.setToolTipText("Aqui limpa tudo, zé! =)");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton20.setText("(");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton21.setText(")");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jButton22.setText("a^b");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton23.setText("√");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton24.setText("f(x)");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton25.setText("g(x)");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton26.setText("[ ]");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_a, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextField_b, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_c, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jTextArea_Historico)
            .addComponent(Calculo)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextArea_Historico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jButton3)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5)
                                .addComponent(jButton6)
                                .addComponent(jButton14)
                                .addComponent(jButton20)
                                .addComponent(jButton21)
                                .addComponent(jButton24)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton8)
                                .addComponent(jButton9)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton10)
                                .addComponent(jButton12)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton13)
                        .addComponent(jButton18)
                        .addComponent(jButton19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton22)
                                .addComponent(jButton23)
                                .addComponent(jButton25))
                            .addComponent(jButton15))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton16)
                            .addComponent(jButton17)
                            .addComponent(jButton26))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTextArea_Historico.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "1";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "2";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "3";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "4";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "5";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "6";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "7";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "8";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "9";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "0";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "%";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + ".";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "+";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "-";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "*";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "/";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton16ActionPerformed
    // Esse é o módulo que atualiza o historico
    private void hito() {
        String to = Calculo.getText();
        if (!to.contains("Valor")) {
            if (!to.contains("para")) {
                String textoHistorico = jTextArea_Historico.getText();
                if (textoHistorico.equals("")) {
                    jTextArea_Historico.setText(textoCalculo + " = " + resultado);
                    System.out.println("bbv");
                } else {
                    String[] linhas = textoHistorico.split("\n");
                    int limite = 5;
                    if (linhas.length < limite) {
                        System.out.println("aa");
                        jTextArea_Historico.setText(textoHistorico + "\n" + textoCalculo + " = " + resultado);
                    } else {
                        String textoAtualizado = "";
                        for (int i = 0; i < limite - 1; i++) {
                            linhas[i] = linhas[i + 1];
                            textoAtualizado = textoAtualizado + linhas[i] + "\n";
                        }
                        textoAtualizado = textoAtualizado + textoCalculo + " = " + resultado + "";
                        jTextArea_Historico.setText(textoAtualizado);
                    }
                }
                Calculo.setText("");
            } else {
                String textoBaskara = to;
                String textoHistorico = jTextArea_Historico.getText();
                if (textoHistorico.equals("")) {
                    jTextArea_Historico.setText(textoBaskara);
                } else {
                    String[] linhas = textoHistorico.split("\n");
                    int limite = 5;
                    if (linhas.length < limite) {
                        jTextArea_Historico.setText(textoHistorico + "\n" + textoBaskara);
                    } else {
                        String textoAtualizado = "";
                        for (int i = 0; i < limite - 1; i++) {
                            linhas[i] = linhas[i + 1];
                            textoAtualizado = textoAtualizado + linhas[i] + "\n";
                        }
                        textoAtualizado = textoAtualizado + textoBaskara;
                        jTextArea_Historico.setText(textoAtualizado);
                    }
                }
                Calculo.setText("");
            }
        } else {
            String colchete = to;
            String textoHistorico = jTextArea_Historico.getText();
            if (textoHistorico.equals("")) {
                jTextArea_Historico.setText(colchete);
            } else {
                String[] linhas = textoHistorico.split("\n");
                int limite = 5;
                if (linhas.length < limite) {
                    jTextArea_Historico.setText(textoHistorico + "\n" + colchete);
                } else {
                    String textoAtualizado = "";
                    for (int i = 0; i < limite - 1; i++) {
                        linhas[i] = linhas[i + 1];
                        textoAtualizado = textoAtualizado + linhas[i] + "\n";
                    }
                    textoAtualizado = textoAtualizado + colchete;
                    jTextArea_Historico.setText(textoAtualizado);
                }
            }
            Calculo.setText("");
        }
    }

    public static Double E(String e) {
        // E --> T + E | T - E | T
        Double numero1 = T(e), numero2;
        char caractere = e.charAt(p);
        if (caractere == ')') {
            p = p + 1;
            return numero1;
        }
        if (p < e.length() && numero1 != null) {
            if (caractere == '+') {
                p = p + 1;
                numero2 = E(e);
                if (numero2 != null) {
                    return numero1 + numero2;
                }
            } else if (caractere == '-') {
                numero2 = E(e);
                if (numero2 != null) {
                    return numero1 + numero2;
                }
            }
        }
        return numero1;
    }

    public static Double T(String e) {
        // T --> F * T | F / T | F
        Double numero1 = R(e), numero2;
        char caractere = e.charAt(p);
        if (caractere == ')') {
            p = p + 1;
            return numero1;
        }
        if (p < e.length() && numero1 != null) {
            if (caractere == '*') {
                p = p + 1;
                numero2 = T(e);
                if (numero2 != null) {
                    return numero1 * numero2;
                }
            }
            if (caractere == '/') {
                p = p + 1;
                numero2 = T(e);
                if (numero2 != null) {
                    return numero1 / numero2;
                }
            }
        }
        return numero1;
    }

    public static Double R(String e) {
        Double numero1 = S(e), numero2;
        char caractere = e.charAt(p);
        if (caractere == ')') {
            p = p + 1;
            return numero1;
        }
        if (p < e.length() && numero1 != null) {
            if (caractere == '^') {
                p = p + 1;
                numero2 = R(e);
                if (numero2 != null) {
                    return Math.pow(numero1, numero2);
                }
            } else if (caractere == '√') {
                p = p + 1;
                numero2 = R(e);
                if (numero2 != null) {
                    return numero1 * Math.sqrt(numero2);
                }
            } else if (caractere == '%') {
                p = p + 1;
                numero2 = R(e);
                if (numero2 != null) {
                    return (numero1 * numero2) / 100;
                }
            }
        } else if (caractere == '√') {
            p = p + 1;
            numero2 = R(e);
            if (numero2 != null) {
                return Math.sqrt(numero2);
            }
        } else if (caractere == '-') {
            p = p + 1;
            numero2 = R(e);
            if (numero2 != null) {
                String nega = "-";
                String contatenar = nega + numero2;
                Double zum = new Double(contatenar);
                return zum;
            }
        }
        return numero1;
    }

    public static Double S(String e) {
        Double numero1 = F(e), numero2;
        char caractere = e.charAt(p);
        if (caractere == '(') {
            p = p + 1;
            return E(e);
        }
        return numero1;
    }

    public static Double F(String e) {
        // F --> num
        String texto = "";
        Double numero = null;
        boolean temPontinho = false;
        boolean temNumero = false;
        char caractere = e.charAt(p);
        while (Character.isDigit(caractere) || caractere == '.') {
            if (temPontinho == false && caractere == '.') {
                texto = texto + caractere;
                temPontinho = true;
            } else {
                if (Character.isDigit(caractere)) {
                    texto = texto + caractere;
                }
            }
            p = p + 1;
            caractere = e.charAt(p);
            temNumero = true;
        }
        if (temNumero) {
            numero = new Double(texto);
        } else {
            if (temPontinho) {
                numero = new Double(texto);
            }
        }

        return numero;
    }
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        textoCalculo = Calculo.getText();
        p = 0;
        textoCalculo = textoCalculo.replace(",", ".");
        resultado = E(textoCalculo.replace(" ", "") + "\0");
        if (resultado == null) {
            jTextArea_Historico.setText("A expressão " + textoCalculo + " está mal formada! =/");
        } else {
            hito();
        }
        /*if (!textoCalculo.contains("X")){
            partes = textoCalculo.split("\\+");
            if (partes.length > 1) {
                double resultado = new Double (partes[0]);
                for (int i = 1; i <= partes.length - 1; i++) {
                    if (!partes[i].equals("")) {
                        double numero = new Double(partes[i]);
                        resultado = resultado + numero;
                    }
                }
                Calculo.setText(textoCalculo+" = "+resultado);

                // Essa parte é para atualizar a tela de histórico.
                hito();
            }
        }
        if (textoCalculo.contains("%")){
            partes = textoCalculo.split("\\%");
            if (partes.length >=1 && !partes[0].equals("")) {
                double resultado = new Double(partes[0]) / 100.0;
                if (partes.length > 1 && !partes[1].equals("")) {
                    resultado = new Double(partes[1]) * resultado;
                }
                Calculo.setText(textoCalculo+" = "+resultado);
                
                // Essa parte é para atualizar a tela de histótico.
                hito();
            }
        }
        if (!textoCalculo.contains("X")){
            partes = textoCalculo.split("\\-");
            if (partes.length > 1) {
                double resultado = new Double (partes[0]);
                for (int i = 1; i <= partes.length - 1; i++) {
                    if (!partes[i].equals("")) {
                        double numero = new Double(partes[i]);
                        resultado = resultado - numero;
                    }
                }

                Calculo.setText(textoCalculo+" = "+resultado);

                // Essa parte é para atualizar a tela de histórico.
                hito();
            }
        }
        if (!textoCalculo.contains("X")){
            partes = textoCalculo.split("\\*");
            if (partes.length > 1) {
                double resultado = new Double (partes[0]);
                for (int i = 1; i <= partes.length - 1; i++) {
                    if (!partes[i].equals("")) {
                        double numero = new Double(partes[i]);
                        resultado = resultado * numero;
                    }
                }
                Calculo.setText(textoCalculo+" = "+resultado);

                // Essa parte é para atualizar a tela de histórico.           
                hito();
            }
        }
        if (!textoCalculo.contains("X")){
            partes = textoCalculo.split("\\/");
            if (partes.length > 1) {
                double resultado = new Double (partes[0]);
                for (int i = 1; i <= partes.length - 1; i++) {
                    if (!partes[i].equals("")) {
                        double numero = new Double(partes[i]);
                        resultado = resultado / numero;
                    }
                }
                Calculo.setText(textoCalculo+" = "+resultado);

                // Essa parte é para atualizar a tela de histórico.           
                hito();
            }
        }*/

        // Aqui começa a parte sobre o delta e a fórmula de Báskara para alguma equação informada.
        if (!jTextField_a.getText().equals("") || !jTextField_b.getText().equals("") || !jTextField_c.getText().equals("")) {
            String textoBaskara = "";
            double a = new Double(jTextField_a.getText().equals("") ? "0.0" : jTextField_a.getText());
            double b = new Double(jTextField_b.getText().equals("") ? "0.0" : jTextField_b.getText());
            double c = new Double(jTextField_c.getText().equals("") ? "0.0" : jTextField_c.getText());
            if (a == 0) {
                textoBaskara = a + "x² + " + b + "x + " + c + " = 0 nem é equação do segundo grau!";
            } else {
                double delta = Math.pow(b, 2) - 4 * a * c;
                if (delta < 0.0) {
                    textoBaskara = "Não existem raízes reais para " + a + "x² + " + b + "x + " + c + " = 0";
                } else {
                    double x1 = (-b - Math.sqrt(delta)) / (2 * a);
                    double x2 = (-b + Math.sqrt(delta)) / (2 * a);
                    if (b >= 0.0 && c >= 0.0) {
                        textoBaskara = "Δ = " + delta + ", x' = " + x1 + " e x\" = " + x2 + " para " + a + "x² + " + b + "x + " + c + " = 0";
                    }
                    if (b >= 0.0 && c < 0.0) {
                        textoBaskara = "Δ = " + delta + ", x' = " + x1 + " e x\" = " + x2 + " para " + a + "x² + " + b + "x " + c + " = 0";
                    }
                    if (b < 0.0 && c >= 0.0) {
                        textoBaskara = "Δ = " + delta + ", x' = " + x1 + " e x\" = " + x2 + " para " + a + "x² " + b + "x + " + c + " = 0";
                    }
                    if (b < 0.0 && c < 0.0) {
                        textoBaskara = "Δ = " + delta + ", x' = " + x1 + " e x\" = " + x2 + " para " + a + "x² " + b + "x " + c + " = 0";
                    }

                }
            }
            jTextField_a.setText("");
            jTextField_b.setText("");
            jTextField_c.setText("");
            Calculo.setText(textoBaskara);

            // Essa parte é para atualizar a tela de histórico.
            hito();
            /*}
        if (textoCalculo.contains("√")){
            String [] ok= textoCalculo.split("√");
            if (!ok[1].equals("")){
                double res = new Double (ok[1]);
                double resulta = Math.sqrt(res);
                Calculo.setText(textoCalculo+" = "+resulta);
            }
            
            // Essa parte é para atualizar a tela de histórico.
            hito();
            
        }
        if (textoCalculo.contains("^")){
            partes = textoCalculo.split("\\^");
            if (partes.length >1) {
                double n1 = new Double (partes[0]);
                double n2 = new Double (partes[1]);
                double resulta = Math.pow(n1, n2);
                Calculo.setText(textoCalculo+" = "+resulta);
            }
            
            // Essa parte é para atualizar a tela de histórico.
            hito();
        }
        if (textoCalculo.contains("X")){
            if (!textoCalculo.contains("²")){
                String [] fun = textoCalculo.split("=");
                double x = new Double (fun[1]);
                double resulta = 4*x-8;
                textoCalculo = "4*"+x+"-8";
                Calculo.setText(textoCalculo+" = "+resulta);
            }else{
                String [] fun = textoCalculo.split("=");
                double x = new Double (fun[1]);
                double resulta = Math.pow(x,2)+2*x-3;
                textoCalculo = x+"²+2*"+x+"-3";
                Calculo.setText(textoCalculo+" = "+resulta);
            }
            
            // Essa parte é para atualizar a tela de histórico.
            hito();
        }
        if (textoCalculo.contains("")){
            
        }*/

        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        String textoCalculo = Calculo.getText();
        if (!textoCalculo.trim().equals("")) {
            Calculo.setText(textoCalculo.substring(0, textoCalculo.length() - 1));
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        Calculo.setText("");
        jTextArea_Historico.setText("");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // ATENÇÃO!!! Será implementado para o terceiro trimestre.
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // ATENÇÃO!!! Será implementado para o terceiro trimestre.
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + "^";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        String textoCalculo = Calculo.getText();
        textoCalculo = textoCalculo + " √";
        Calculo.setText(textoCalculo);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        String texto = "4X-8  X=";
        Calculo.setText(texto);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        String texto = "X²+2X-3  X=";
        Calculo.setText(texto);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        String t = Calculo.getText();
        int cont = new Integer(t);
        if (cont > 0) {
            if (cont < 7) {
                double[][][] textoCalculof = new double[7][7][7];
                double resultadof = 0.0;
                String fra = "  ";
                String fraci[] = new String[7];
                String facri = "";
                for (int i = 1; i <= cont; i++) {
                    textoCalculof[i][0][0] = (2 * i - 1);
                    textoCalculof[0][i][0] = (3 * i);
                    textoCalculof[0][0][i] = textoCalculof[i][0][0] / textoCalculof[0][i][0];
                    DecimalFormat df = new DecimalFormat("#.##");
                    fraci[i] = df.format(textoCalculof[0][0][i]);
                    if (i < cont && i == 1) {
                        facri = facri + "    " + fraci[i];
                    }
                    if (i < cont && i == 2) {
                        facri = facri + "          " + fraci[i];
                    }
                    if (i < cont && i == 3) {
                        facri = facri + "        " + fraci[i];
                    }
                    if (i < cont && i == 4) {
                        facri = facri + "          " + fraci[i];
                    }
                    if (i < cont && i == 5) {
                        facri = facri + "           " + fraci[i];
                    }
                    if (i == cont && i == 6) {
                        facri = facri + "              " + fraci[i] + "      ";
                    }
                    if (i < cont) {
                        fra = fra + textoCalculof[i][0][0] + "/" + textoCalculof[0][i][0] + " + ";
                    }
                    if (i == cont) {
                        fra = fra + textoCalculof[i][0][0] + "/" + textoCalculof[0][i][0];
                    }
                    resultadof = textoCalculof[0][0][i] + resultadof;
                }
                textoCalculo = fra;
                resultado = resultadof;
                DecimalFormat df = new DecimalFormat("#.##");
                Calculo.setText(textoCalculo + " = " + (df.format(resultado)));

                // Essa parte é para atualizar o histórico.
                hito();
                textoCalculo = facri;
                hito();
            } else {
                Calculo.setText("Valor muito grande.");
                // Essa parte é para atualizar o histórico.
                hito();
            }
        } else {

            Calculo.setText("Valor indisponível.");
            // Essa parte é para atualizar o histórico.
            hito();
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelinhaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelinhaCalculadora().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Calculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea_Historico;
    private javax.swing.JTextField jTextField_a;
    private javax.swing.JTextField jTextField_b;
    private javax.swing.JTextField jTextField_c;
    // End of variables declaration//GEN-END:variables
}
